Name:         kube-prometheus-kube-prome-kubernetes-system-controller-manager
Namespace:    monitoring-stack
Labels:       app=kube-prometheus-stack
              app.kubernetes.io/instance=kube-prometheus
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/part-of=kube-prometheus-stack
              app.kubernetes.io/version=60.3.0
              chart=kube-prometheus-stack-60.3.0
              heritage=Helm
              release=kube-prometheus
Annotations:  prometheus-operator-validated: true
API Version:  monitoring.coreos.com/v1
Kind:         PrometheusRule
Metadata:
  Creation Timestamp:  2024-06-23T14:10:16Z
  Generation:          1
  Resource Version:    38671
  UID:                 278c8ff6-72d5-4996-ab41-074c13b479ca
Spec:
  Groups:
    Name:  kubernetes-system-controller-manager
    Rules:
      Alert:  KubeControllerManagerDown
      Annotations:
        Description:  KubeControllerManager has disappeared from Prometheus target discovery.
        runbook_url:  https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubecontrollermanagerdown
        Summary:      Target disappeared from Prometheus target discovery.
      Expr:           absent(up{job="kube-controller-manager"} == 1)
      For:            15m
      Labels:
        Severity:  critical
Events:            <none>
